[package]
name = "sakujestrashbot2"
version = "1.0.0"
authors = ["geni"]

[dependencies]
rand = "0.3.0"
egg-mode = "0.12.0"
tokio-core = "0.1"
chrono = "0.4"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"